// Code generated by protoc-gen-go. DO NOT EDIT.
// source: prize.service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCurrentPrizeResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	IsWon                bool     `protobuf:"varint,3,opt,name=isWon,proto3" json:"isWon,omitempty"`
	Photos               []string `protobuf:"bytes,4,rep,name=photos,proto3" json:"photos,omitempty"`
	Riddle               string   `protobuf:"bytes,5,opt,name=riddle,proto3" json:"riddle,omitempty"`
	GuessCount           uint64   `protobuf:"varint,6,opt,name=guessCount,proto3" json:"guessCount,omitempty"`
	AvailableHints       uint64   `protobuf:"varint,7,opt,name=availableHints,proto3" json:"availableHints,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentPrizeResponse) Reset()         { *m = GetCurrentPrizeResponse{} }
func (m *GetCurrentPrizeResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentPrizeResponse) ProtoMessage()    {}
func (*GetCurrentPrizeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1d84702731a7a2f, []int{0}
}

func (m *GetCurrentPrizeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentPrizeResponse.Unmarshal(m, b)
}
func (m *GetCurrentPrizeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentPrizeResponse.Marshal(b, m, deterministic)
}
func (m *GetCurrentPrizeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentPrizeResponse.Merge(m, src)
}
func (m *GetCurrentPrizeResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrentPrizeResponse.Size(m)
}
func (m *GetCurrentPrizeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentPrizeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentPrizeResponse proto.InternalMessageInfo

func (m *GetCurrentPrizeResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetCurrentPrizeResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetCurrentPrizeResponse) GetIsWon() bool {
	if m != nil {
		return m.IsWon
	}
	return false
}

func (m *GetCurrentPrizeResponse) GetPhotos() []string {
	if m != nil {
		return m.Photos
	}
	return nil
}

func (m *GetCurrentPrizeResponse) GetRiddle() string {
	if m != nil {
		return m.Riddle
	}
	return ""
}

func (m *GetCurrentPrizeResponse) GetGuessCount() uint64 {
	if m != nil {
		return m.GuessCount
	}
	return 0
}

func (m *GetCurrentPrizeResponse) GetAvailableHints() uint64 {
	if m != nil {
		return m.AvailableHints
	}
	return 0
}

type AnswerRiddleRequest struct {
	Answer               string   `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerRiddleRequest) Reset()         { *m = AnswerRiddleRequest{} }
func (m *AnswerRiddleRequest) String() string { return proto.CompactTextString(m) }
func (*AnswerRiddleRequest) ProtoMessage()    {}
func (*AnswerRiddleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1d84702731a7a2f, []int{1}
}

func (m *AnswerRiddleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerRiddleRequest.Unmarshal(m, b)
}
func (m *AnswerRiddleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerRiddleRequest.Marshal(b, m, deterministic)
}
func (m *AnswerRiddleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerRiddleRequest.Merge(m, src)
}
func (m *AnswerRiddleRequest) XXX_Size() int {
	return xxx_messageInfo_AnswerRiddleRequest.Size(m)
}
func (m *AnswerRiddleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerRiddleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerRiddleRequest proto.InternalMessageInfo

func (m *AnswerRiddleRequest) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type AnswerRiddleResponse struct {
	IsCorrect            bool     `protobuf:"varint,1,opt,name=isCorrect,proto3" json:"isCorrect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnswerRiddleResponse) Reset()         { *m = AnswerRiddleResponse{} }
func (m *AnswerRiddleResponse) String() string { return proto.CompactTextString(m) }
func (*AnswerRiddleResponse) ProtoMessage()    {}
func (*AnswerRiddleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1d84702731a7a2f, []int{2}
}

func (m *AnswerRiddleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnswerRiddleResponse.Unmarshal(m, b)
}
func (m *AnswerRiddleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnswerRiddleResponse.Marshal(b, m, deterministic)
}
func (m *AnswerRiddleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnswerRiddleResponse.Merge(m, src)
}
func (m *AnswerRiddleResponse) XXX_Size() int {
	return xxx_messageInfo_AnswerRiddleResponse.Size(m)
}
func (m *AnswerRiddleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnswerRiddleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnswerRiddleResponse proto.InternalMessageInfo

func (m *AnswerRiddleResponse) GetIsCorrect() bool {
	if m != nil {
		return m.IsCorrect
	}
	return false
}

func init() {
	proto.RegisterType((*GetCurrentPrizeResponse)(nil), "api.GetCurrentPrizeResponse")
	proto.RegisterType((*AnswerRiddleRequest)(nil), "api.AnswerRiddleRequest")
	proto.RegisterType((*AnswerRiddleResponse)(nil), "api.AnswerRiddleResponse")
}

func init() { proto.RegisterFile("prize.service.proto", fileDescriptor_d1d84702731a7a2f) }

var fileDescriptor_d1d84702731a7a2f = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x49, 0xff, 0x6c, 0x2e, 0xa5, 0xc2, 0xb4, 0xe8, 0x58, 0x8a, 0x84, 0x2c, 0x24, 0x1b,
	0xb3, 0x50, 0x77, 0xae, 0x24, 0x88, 0x2e, 0x65, 0x5c, 0xb8, 0x4e, 0x9b, 0x8b, 0x5e, 0x88, 0x99,
	0x71, 0xe6, 0xa6, 0xa2, 0x4f, 0xe1, 0x8b, 0xf9, 0x4e, 0x92, 0x49, 0xc0, 0x5a, 0xea, 0x6e, 0xce,
	0x37, 0xf7, 0x67, 0xce, 0x19, 0x98, 0x19, 0x4b, 0x9f, 0x98, 0x3a, 0xb4, 0x1b, 0x5a, 0x63, 0x6a,
	0xac, 0x66, 0x2d, 0xfa, 0xb9, 0xa1, 0x05, 0xd4, 0x4c, 0x65, 0x0b, 0xe2, 0xef, 0x00, 0x8e, 0xef,
	0x90, 0xb3, 0xda, 0x5a, 0xac, 0xf8, 0xa1, 0x69, 0x51, 0xe8, 0x8c, 0xae, 0x1c, 0x8a, 0x29, 0xf4,
	0xa8, 0x90, 0x41, 0x14, 0x24, 0x03, 0xd5, 0xa3, 0x42, 0xcc, 0x61, 0xc8, 0xc4, 0x25, 0xca, 0x5e,
	0x14, 0x24, 0xa1, 0x6a, 0x45, 0x43, 0xc9, 0x3d, 0xe9, 0x4a, 0xf6, 0xa3, 0x20, 0x19, 0xab, 0x56,
	0x88, 0x23, 0x18, 0x99, 0x17, 0xcd, 0xda, 0xc9, 0x41, 0xd4, 0x4f, 0x42, 0xd5, 0xa9, 0x86, 0x5b,
	0x2a, 0x8a, 0x12, 0xe5, 0xd0, 0x0f, 0xe9, 0x94, 0x38, 0x05, 0x78, 0xae, 0xd1, 0xb9, 0x4c, 0xd7,
	0x15, 0xcb, 0x91, 0xdf, 0xb9, 0x45, 0xc4, 0x19, 0x4c, 0xf3, 0x4d, 0x4e, 0x65, 0xbe, 0x2a, 0xf1,
	0x9e, 0x2a, 0x76, 0xf2, 0xc0, 0xd7, 0xec, 0xd0, 0xf8, 0x1c, 0x66, 0x37, 0x95, 0x7b, 0x47, 0xab,
	0xfc, 0x5c, 0x85, 0x6f, 0x35, 0x3a, 0x6e, 0xd6, 0xe6, 0x1e, 0x7b, 0x3b, 0xa1, 0xea, 0x54, 0x7c,
	0x05, 0xf3, 0xbf, 0xe5, 0x9d, 0xf5, 0x25, 0x84, 0xe4, 0x32, 0x6d, 0x2d, 0xae, 0xd9, 0xb7, 0x8c,
	0xd5, 0x2f, 0xb8, 0xf8, 0x0a, 0x60, 0xe2, 0xa3, 0x7a, 0x6c, 0xc3, 0x15, 0xd7, 0x70, 0xb8, 0x13,
	0xa2, 0x80, 0x34, 0x37, 0x94, 0xde, 0xbe, 0x1a, 0xfe, 0x58, 0x2c, 0xfd, 0xf9, 0xbf, 0x98, 0x33,
	0x98, 0x6c, 0xbf, 0x41, 0x48, 0x5f, 0xbd, 0xc7, 0xc5, 0xe2, 0x64, 0xcf, 0x4d, 0x3b, 0x64, 0x35,
	0xf2, 0xdf, 0x79, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x61, 0xa3, 0xd7, 0xde, 0xf6, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PrizeServiceClient is the client API for PrizeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrizeServiceClient interface {
	GetCurrentPrize(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCurrentPrizeResponse, error)
	AnswerRiddle(ctx context.Context, in *AnswerRiddleRequest, opts ...grpc.CallOption) (*AnswerRiddleResponse, error)
}

type prizeServiceClient struct {
	cc *grpc.ClientConn
}

func NewPrizeServiceClient(cc *grpc.ClientConn) PrizeServiceClient {
	return &prizeServiceClient{cc}
}

func (c *prizeServiceClient) GetCurrentPrize(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCurrentPrizeResponse, error) {
	out := new(GetCurrentPrizeResponse)
	err := c.cc.Invoke(ctx, "/api.PrizeService/GetCurrentPrize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *prizeServiceClient) AnswerRiddle(ctx context.Context, in *AnswerRiddleRequest, opts ...grpc.CallOption) (*AnswerRiddleResponse, error) {
	out := new(AnswerRiddleResponse)
	err := c.cc.Invoke(ctx, "/api.PrizeService/AnswerRiddle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrizeServiceServer is the server API for PrizeService service.
type PrizeServiceServer interface {
	GetCurrentPrize(context.Context, *Empty) (*GetCurrentPrizeResponse, error)
	AnswerRiddle(context.Context, *AnswerRiddleRequest) (*AnswerRiddleResponse, error)
}

// UnimplementedPrizeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPrizeServiceServer struct {
}

func (*UnimplementedPrizeServiceServer) GetCurrentPrize(ctx context.Context, req *Empty) (*GetCurrentPrizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentPrize not implemented")
}
func (*UnimplementedPrizeServiceServer) AnswerRiddle(ctx context.Context, req *AnswerRiddleRequest) (*AnswerRiddleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnswerRiddle not implemented")
}

func RegisterPrizeServiceServer(s *grpc.Server, srv PrizeServiceServer) {
	s.RegisterService(&_PrizeService_serviceDesc, srv)
}

func _PrizeService_GetCurrentPrize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrizeServiceServer).GetCurrentPrize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrizeService/GetCurrentPrize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrizeServiceServer).GetCurrentPrize(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PrizeService_AnswerRiddle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnswerRiddleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrizeServiceServer).AnswerRiddle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PrizeService/AnswerRiddle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrizeServiceServer).AnswerRiddle(ctx, req.(*AnswerRiddleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrizeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PrizeService",
	HandlerType: (*PrizeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentPrize",
			Handler:    _PrizeService_GetCurrentPrize_Handler,
		},
		{
			MethodName: "AnswerRiddle",
			Handler:    _PrizeService_AnswerRiddle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prize.service.proto",
}
