// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SignupRequest struct {
	FirebaseUid          string   `protobuf:"bytes,1,opt,name=firebaseUid,proto3" json:"firebaseUid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{0}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetFirebaseUid() string {
	if m != nil {
		return m.FirebaseUid
	}
	return ""
}

func (m *SignupRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SignupRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetCurrentUserResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	GuessTokens          uint64   `protobuf:"varint,4,opt,name=guessTokens,proto3" json:"guessTokens,omitempty"`
	SoonestNextGuess     int64    `protobuf:"varint,5,opt,name=soonestNextGuess,proto3" json:"soonestNextGuess,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCurrentUserResponse) Reset()         { *m = GetCurrentUserResponse{} }
func (m *GetCurrentUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentUserResponse) ProtoMessage()    {}
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e7ed9320702f2c5, []int{1}
}

func (m *GetCurrentUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCurrentUserResponse.Unmarshal(m, b)
}
func (m *GetCurrentUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCurrentUserResponse.Marshal(b, m, deterministic)
}
func (m *GetCurrentUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCurrentUserResponse.Merge(m, src)
}
func (m *GetCurrentUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetCurrentUserResponse.Size(m)
}
func (m *GetCurrentUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCurrentUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCurrentUserResponse proto.InternalMessageInfo

func (m *GetCurrentUserResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetCurrentUserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetCurrentUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetCurrentUserResponse) GetGuessTokens() uint64 {
	if m != nil {
		return m.GuessTokens
	}
	return 0
}

func (m *GetCurrentUserResponse) GetSoonestNextGuess() int64 {
	if m != nil {
		return m.SoonestNextGuess
	}
	return 0
}

func init() {
	proto.RegisterType((*SignupRequest)(nil), "api.SignupRequest")
	proto.RegisterType((*GetCurrentUserResponse)(nil), "api.GetCurrentUserResponse")
}

func init() { proto.RegisterFile("user.service.proto", fileDescriptor_1e7ed9320702f2c5) }

var fileDescriptor_1e7ed9320702f2c5 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0xdd, 0xb6, 0xe8, 0x14, 0x8b, 0x0c, 0x22, 0x61, 0xbd, 0x2c, 0x3d, 0x2d, 0x1e,
	0xf6, 0xa0, 0x27, 0xcf, 0x22, 0xbd, 0x79, 0x48, 0xed, 0x03, 0xa4, 0x75, 0x2c, 0xc1, 0x6e, 0x12,
	0x33, 0x89, 0xe8, 0x1b, 0xf9, 0x98, 0xb2, 0x59, 0x91, 0x5d, 0xf4, 0xd4, 0x5b, 0xe6, 0xfb, 0xe1,
	0xcf, 0xe4, 0x0b, 0x60, 0x64, 0xf2, 0x0d, 0x93, 0x7f, 0xd7, 0x3b, 0x6a, 0x9c, 0xb7, 0xc1, 0x62,
	0xa1, 0x9c, 0x2e, 0x21, 0x06, 0x7d, 0xe8, 0xc1, 0x72, 0x07, 0x67, 0x6b, 0xbd, 0x37, 0xd1, 0x49,
	0x7a, 0x8b, 0xc4, 0x01, 0x2b, 0x98, 0xbf, 0x68, 0x4f, 0x5b, 0xc5, 0xb4, 0xd1, 0xcf, 0x22, 0xab,
	0xb2, 0xfa, 0x54, 0x0e, 0x11, 0x96, 0x70, 0xd2, 0x35, 0x1b, 0xd5, 0x92, 0xc8, 0x53, 0xfc, 0x3b,
	0xe3, 0x05, 0x4c, 0xa9, 0x55, 0xfa, 0x20, 0x8a, 0x14, 0xf4, 0xc3, 0xf2, 0x2b, 0x83, 0xcb, 0x15,
	0x85, 0xfb, 0xe8, 0x3d, 0x99, 0xb0, 0x61, 0xf2, 0x92, 0xd8, 0x59, 0xc3, 0x84, 0x0b, 0xc8, 0x7f,
	0x6e, 0x99, 0xc8, 0xfc, 0x98, 0xf2, 0x6e, 0xe1, 0x7d, 0x24, 0xe6, 0x27, 0xfb, 0x4a, 0x86, 0xc5,
	0x24, 0x55, 0x0d, 0x11, 0x5e, 0xc3, 0x39, 0x5b, 0x6b, 0x88, 0xc3, 0x23, 0x7d, 0x84, 0x55, 0x97,
	0x88, 0x69, 0x95, 0xd5, 0x85, 0xfc, 0xc3, 0x6f, 0x3c, 0xcc, 0xbb, 0xfd, 0xd6, 0xbd, 0x35, 0xac,
	0x61, 0xd6, 0xeb, 0x41, 0x6c, 0x94, 0xd3, 0xcd, 0xc8, 0x55, 0x09, 0x89, 0x3d, 0xb4, 0x2e, 0x7c,
	0xe2, 0x1d, 0x2c, 0xc6, 0x4f, 0xc4, 0x41, 0x5a, 0x5e, 0xa5, 0xf3, 0xff, 0x0e, 0xb6, 0xb3, 0xf4,
	0x15, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2b, 0xd7, 0xf5, 0x45, 0xb1, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*Empty, error)
	GetCurrentUser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCurrentUserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/api.UserService/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetCurrentUser(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetCurrentUserResponse, error) {
	out := new(GetCurrentUserResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/GetCurrentUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Signup(context.Context, *SignupRequest) (*Empty, error)
	GetCurrentUser(context.Context, *Empty) (*GetCurrentUserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Signup(ctx context.Context, req *SignupRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedUserServiceServer) GetCurrentUser(ctx context.Context, req *Empty) (*GetCurrentUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/GetCurrentUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetCurrentUser(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _UserService_Signup_Handler,
		},
		{
			MethodName: "GetCurrentUser",
			Handler:    _UserService_GetCurrentUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.service.proto",
}
