// Code generated by protoc-gen-go. DO NOT EDIT.
// source: winner.service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWinnersResponse struct {
	Winners              []*Winner `protobuf:"bytes,1,rep,name=winners,proto3" json:"winners,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetWinnersResponse) Reset()         { *m = GetWinnersResponse{} }
func (m *GetWinnersResponse) String() string { return proto.CompactTextString(m) }
func (*GetWinnersResponse) ProtoMessage()    {}
func (*GetWinnersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f814ad39e50705d2, []int{0}
}

func (m *GetWinnersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWinnersResponse.Unmarshal(m, b)
}
func (m *GetWinnersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWinnersResponse.Marshal(b, m, deterministic)
}
func (m *GetWinnersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWinnersResponse.Merge(m, src)
}
func (m *GetWinnersResponse) XXX_Size() int {
	return xxx_messageInfo_GetWinnersResponse.Size(m)
}
func (m *GetWinnersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWinnersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWinnersResponse proto.InternalMessageInfo

func (m *GetWinnersResponse) GetWinners() []*Winner {
	if m != nil {
		return m.Winners
	}
	return nil
}

type Winner struct {
	PrizeId              uint64   `protobuf:"varint,1,opt,name=prizeId,proto3" json:"prizeId,omitempty"`
	PrizeTitle           string   `protobuf:"bytes,2,opt,name=prizeTitle,proto3" json:"prizeTitle,omitempty"`
	PrizeMarketPrice     float32  `protobuf:"fixed32,3,opt,name=prizeMarketPrice,proto3" json:"prizeMarketPrice,omitempty"`
	PrizePhotos          []string `protobuf:"bytes,4,rep,name=prizePhotos,proto3" json:"prizePhotos,omitempty"`
	GuessCount           uint64   `protobuf:"varint,5,opt,name=guessCount,proto3" json:"guessCount,omitempty"`
	Riddle               string   `protobuf:"bytes,6,opt,name=riddle,proto3" json:"riddle,omitempty"`
	AcceptedAnswer       string   `protobuf:"bytes,7,opt,name=acceptedAnswer,proto3" json:"acceptedAnswer,omitempty"`
	TimeOfWin            int64    `protobuf:"varint,8,opt,name=timeOfWin,proto3" json:"timeOfWin,omitempty"`
	WinnerId             uint64   `protobuf:"varint,9,opt,name=winnerId,proto3" json:"winnerId,omitempty"`
	WinnerName           string   `protobuf:"bytes,10,opt,name=winnerName,proto3" json:"winnerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Winner) Reset()         { *m = Winner{} }
func (m *Winner) String() string { return proto.CompactTextString(m) }
func (*Winner) ProtoMessage()    {}
func (*Winner) Descriptor() ([]byte, []int) {
	return fileDescriptor_f814ad39e50705d2, []int{1}
}

func (m *Winner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Winner.Unmarshal(m, b)
}
func (m *Winner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Winner.Marshal(b, m, deterministic)
}
func (m *Winner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Winner.Merge(m, src)
}
func (m *Winner) XXX_Size() int {
	return xxx_messageInfo_Winner.Size(m)
}
func (m *Winner) XXX_DiscardUnknown() {
	xxx_messageInfo_Winner.DiscardUnknown(m)
}

var xxx_messageInfo_Winner proto.InternalMessageInfo

func (m *Winner) GetPrizeId() uint64 {
	if m != nil {
		return m.PrizeId
	}
	return 0
}

func (m *Winner) GetPrizeTitle() string {
	if m != nil {
		return m.PrizeTitle
	}
	return ""
}

func (m *Winner) GetPrizeMarketPrice() float32 {
	if m != nil {
		return m.PrizeMarketPrice
	}
	return 0
}

func (m *Winner) GetPrizePhotos() []string {
	if m != nil {
		return m.PrizePhotos
	}
	return nil
}

func (m *Winner) GetGuessCount() uint64 {
	if m != nil {
		return m.GuessCount
	}
	return 0
}

func (m *Winner) GetRiddle() string {
	if m != nil {
		return m.Riddle
	}
	return ""
}

func (m *Winner) GetAcceptedAnswer() string {
	if m != nil {
		return m.AcceptedAnswer
	}
	return ""
}

func (m *Winner) GetTimeOfWin() int64 {
	if m != nil {
		return m.TimeOfWin
	}
	return 0
}

func (m *Winner) GetWinnerId() uint64 {
	if m != nil {
		return m.WinnerId
	}
	return 0
}

func (m *Winner) GetWinnerName() string {
	if m != nil {
		return m.WinnerName
	}
	return ""
}

func init() {
	proto.RegisterType((*GetWinnersResponse)(nil), "api.GetWinnersResponse")
	proto.RegisterType((*Winner)(nil), "api.Winner")
}

func init() { proto.RegisterFile("winner.service.proto", fileDescriptor_f814ad39e50705d2) }

var fileDescriptor_f814ad39e50705d2 = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0x6e, 0xdd, 0x76, 0xa7, 0x28, 0x32, 0x88, 0x86, 0x22, 0x12, 0x0a, 0xca, 0xe2,
	0x61, 0xc1, 0x7a, 0xf4, 0xa4, 0x22, 0xd2, 0x83, 0x5a, 0xa2, 0xd0, 0xf3, 0xba, 0x3b, 0x6a, 0xb0,
	0xdd, 0x84, 0x24, 0xb5, 0xe8, 0x4f, 0xf4, 0x57, 0x49, 0x13, 0x6b, 0x17, 0x7b, 0x9b, 0xf7, 0x65,
	0xc2, 0x3c, 0xde, 0x83, 0xbd, 0x85, 0xac, 0x6b, 0x32, 0xb9, 0x25, 0xf3, 0x21, 0x4b, 0xca, 0xb5,
	0x51, 0x4e, 0x61, 0x5c, 0x68, 0xd9, 0x87, 0xb9, 0x93, 0xd3, 0x00, 0x06, 0x17, 0x80, 0xb7, 0xe4,
	0x26, 0x7e, 0xd7, 0x0a, 0xb2, 0x5a, 0xd5, 0x96, 0xf0, 0x18, 0x3a, 0xe1, 0xbb, 0x65, 0x11, 0x8f,
	0xb3, 0xde, 0xb0, 0x97, 0x17, 0x5a, 0xe6, 0x61, 0x4d, 0xac, 0xde, 0x06, 0xdf, 0x2d, 0x48, 0x02,
	0x43, 0x06, 0x1d, 0x6d, 0xe4, 0x17, 0x8d, 0x2a, 0x16, 0xf1, 0x28, 0x6b, 0x8b, 0x95, 0xc4, 0x23,
	0x00, 0x3f, 0x3e, 0x49, 0x37, 0x25, 0xd6, 0xe2, 0x51, 0x96, 0x8a, 0x06, 0xc1, 0x53, 0xd8, 0xf5,
	0xea, 0xae, 0x30, 0xef, 0xe4, 0xc6, 0x46, 0x96, 0xc4, 0x62, 0x1e, 0x65, 0x2d, 0xb1, 0xc1, 0x91,
	0x43, 0xcf, 0xb3, 0xf1, 0x9b, 0x72, 0xca, 0xb2, 0x36, 0x8f, 0xb3, 0x54, 0x34, 0xd1, 0xf2, 0xda,
	0xeb, 0x9c, 0xac, 0xbd, 0x56, 0xf3, 0xda, 0xb1, 0x2d, 0x6f, 0xa5, 0x41, 0x70, 0x1f, 0x12, 0x23,
	0xab, 0x6a, 0x4a, 0x2c, 0xf1, 0x4e, 0x7e, 0x15, 0x9e, 0xc0, 0x4e, 0x51, 0x96, 0xa4, 0x1d, 0x55,
	0x97, 0xb5, 0x5d, 0x90, 0x61, 0x1d, 0xff, 0xfe, 0x8f, 0xe2, 0x21, 0xa4, 0x4e, 0xce, 0xe8, 0xe1,
	0x65, 0x22, 0x6b, 0xd6, 0xe5, 0x51, 0x16, 0x8b, 0x35, 0xc0, 0x3e, 0x74, 0x43, 0x36, 0xa3, 0x8a,
	0xa5, 0xfe, 0xf6, 0x9f, 0x5e, 0x3a, 0x0b, 0xf3, 0x7d, 0x31, 0x23, 0x06, 0x21, 0x87, 0x35, 0x19,
	0x5e, 0xc1, 0x76, 0xc8, 0xf2, 0x31, 0x34, 0x86, 0x67, 0x00, 0xeb, 0x6a, 0x10, 0x7c, 0x03, 0x37,
	0x33, 0xed, 0x3e, 0xfb, 0x07, 0x7e, 0xde, 0xec, 0xed, 0x39, 0xf1, 0xa5, 0x9e, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xd7, 0xd3, 0xae, 0x23, 0xfd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WinnerServiceClient is the client API for WinnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WinnerServiceClient interface {
	GetWinners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetWinnersResponse, error)
}

type winnerServiceClient struct {
	cc *grpc.ClientConn
}

func NewWinnerServiceClient(cc *grpc.ClientConn) WinnerServiceClient {
	return &winnerServiceClient{cc}
}

func (c *winnerServiceClient) GetWinners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetWinnersResponse, error) {
	out := new(GetWinnersResponse)
	err := c.cc.Invoke(ctx, "/api.WinnerService/GetWinners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WinnerServiceServer is the server API for WinnerService service.
type WinnerServiceServer interface {
	GetWinners(context.Context, *Empty) (*GetWinnersResponse, error)
}

// UnimplementedWinnerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWinnerServiceServer struct {
}

func (*UnimplementedWinnerServiceServer) GetWinners(ctx context.Context, req *Empty) (*GetWinnersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWinners not implemented")
}

func RegisterWinnerServiceServer(s *grpc.Server, srv WinnerServiceServer) {
	s.RegisterService(&_WinnerService_serviceDesc, srv)
}

func _WinnerService_GetWinners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WinnerServiceServer).GetWinners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WinnerService/GetWinners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WinnerServiceServer).GetWinners(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _WinnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WinnerService",
	HandlerType: (*WinnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWinners",
			Handler:    _WinnerService_GetWinners_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "winner.service.proto",
}
