// Code generated by protoc-gen-go. DO NOT EDIT.
// source: winner.service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWinnersResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PrizeTitle           string   `protobuf:"bytes,2,opt,name=prizeTitle,proto3" json:"prizeTitle,omitempty"`
	PrizeMarketPrice     float32  `protobuf:"fixed32,3,opt,name=prizeMarketPrice,proto3" json:"prizeMarketPrice,omitempty"`
	GuessCount           uint64   `protobuf:"varint,4,opt,name=guessCount,proto3" json:"guessCount,omitempty"`
	Riddle               string   `protobuf:"bytes,5,opt,name=riddle,proto3" json:"riddle,omitempty"`
	AcceptedAnswer       string   `protobuf:"bytes,6,opt,name=acceptedAnswer,proto3" json:"acceptedAnswer,omitempty"`
	TimeOfWin            int64    `protobuf:"varint,7,opt,name=timeOfWin,proto3" json:"timeOfWin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWinnersResponse) Reset()         { *m = GetWinnersResponse{} }
func (m *GetWinnersResponse) String() string { return proto.CompactTextString(m) }
func (*GetWinnersResponse) ProtoMessage()    {}
func (*GetWinnersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f814ad39e50705d2, []int{0}
}

func (m *GetWinnersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWinnersResponse.Unmarshal(m, b)
}
func (m *GetWinnersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWinnersResponse.Marshal(b, m, deterministic)
}
func (m *GetWinnersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWinnersResponse.Merge(m, src)
}
func (m *GetWinnersResponse) XXX_Size() int {
	return xxx_messageInfo_GetWinnersResponse.Size(m)
}
func (m *GetWinnersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWinnersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetWinnersResponse proto.InternalMessageInfo

func (m *GetWinnersResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetWinnersResponse) GetPrizeTitle() string {
	if m != nil {
		return m.PrizeTitle
	}
	return ""
}

func (m *GetWinnersResponse) GetPrizeMarketPrice() float32 {
	if m != nil {
		return m.PrizeMarketPrice
	}
	return 0
}

func (m *GetWinnersResponse) GetGuessCount() uint64 {
	if m != nil {
		return m.GuessCount
	}
	return 0
}

func (m *GetWinnersResponse) GetRiddle() string {
	if m != nil {
		return m.Riddle
	}
	return ""
}

func (m *GetWinnersResponse) GetAcceptedAnswer() string {
	if m != nil {
		return m.AcceptedAnswer
	}
	return ""
}

func (m *GetWinnersResponse) GetTimeOfWin() int64 {
	if m != nil {
		return m.TimeOfWin
	}
	return 0
}

func init() {
	proto.RegisterType((*GetWinnersResponse)(nil), "api.GetWinnersResponse")
}

func init() { proto.RegisterFile("winner.service.proto", fileDescriptor_f814ad39e50705d2) }

var fileDescriptor_f814ad39e50705d2 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xd9, 0xb4, 0x46, 0x3a, 0x60, 0x91, 0x41, 0x74, 0x29, 0x22, 0xc1, 0x83, 0x04, 0x0f,
	0x41, 0xec, 0x13, 0x88, 0x8a, 0x27, 0x51, 0x56, 0xa1, 0xe7, 0x98, 0x1d, 0x65, 0x30, 0xdd, 0x2c,
	0xbb, 0x13, 0x8b, 0x3e, 0xb4, 0xcf, 0x20, 0x6e, 0x84, 0x16, 0x7b, 0xdb, 0xff, 0xdb, 0x61, 0x7e,
	0xe6, 0x83, 0x83, 0x15, 0x3b, 0x47, 0xa1, 0x8a, 0x14, 0x3e, 0xb8, 0xa1, 0xca, 0x87, 0x4e, 0x3a,
	0x1c, 0xd5, 0x9e, 0x67, 0xd0, 0x0b, 0xb7, 0x03, 0x38, 0xfd, 0x56, 0x80, 0x77, 0x24, 0x8b, 0x34,
	0x1c, 0x0d, 0x45, 0xdf, 0xb9, 0x48, 0x38, 0x85, 0x8c, 0xad, 0x56, 0x85, 0x2a, 0xc7, 0x26, 0x63,
	0x8b, 0x27, 0x00, 0x3e, 0xf0, 0x17, 0x3d, 0xb3, 0xb4, 0xa4, 0xb3, 0x42, 0x95, 0x13, 0xb3, 0x41,
	0xf0, 0x1c, 0xf6, 0x53, 0xba, 0xaf, 0xc3, 0x3b, 0xc9, 0x63, 0xe0, 0x86, 0xf4, 0xa8, 0x50, 0x65,
	0x66, 0xb6, 0xf8, 0xef, 0xae, 0xb7, 0x9e, 0x62, 0xbc, 0xee, 0x7a, 0x27, 0x7a, 0x9c, 0x3a, 0x36,
	0x08, 0x1e, 0x42, 0x1e, 0xd8, 0xda, 0x96, 0xf4, 0x4e, 0xea, 0xf9, 0x4b, 0x78, 0x06, 0xd3, 0xba,
	0x69, 0xc8, 0x0b, 0xd9, 0x2b, 0x17, 0x57, 0x14, 0x74, 0x9e, 0xfe, 0xff, 0x51, 0x3c, 0x86, 0x89,
	0xf0, 0x92, 0x1e, 0x5e, 0x17, 0xec, 0xf4, 0x6e, 0xa1, 0xca, 0x91, 0x59, 0x83, 0xcb, 0x1b, 0xd8,
	0x1b, 0x8e, 0x7d, 0x1a, 0xc4, 0xe0, 0x1c, 0x60, 0x2d, 0x00, 0xa1, 0xaa, 0x3d, 0x57, 0xb7, 0x4b,
	0x2f, 0x9f, 0xb3, 0xa3, 0xf4, 0xde, 0xb6, 0x73, 0xa1, 0x5e, 0xf2, 0x64, 0x6f, 0xfe, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xe7, 0x5c, 0xb6, 0x9a, 0x66, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WinnerServiceClient is the client API for WinnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WinnerServiceClient interface {
	GetWinners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (WinnerService_GetWinnersClient, error)
}

type winnerServiceClient struct {
	cc *grpc.ClientConn
}

func NewWinnerServiceClient(cc *grpc.ClientConn) WinnerServiceClient {
	return &winnerServiceClient{cc}
}

func (c *winnerServiceClient) GetWinners(ctx context.Context, in *Empty, opts ...grpc.CallOption) (WinnerService_GetWinnersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WinnerService_serviceDesc.Streams[0], "/api.WinnerService/GetWinners", opts...)
	if err != nil {
		return nil, err
	}
	x := &winnerServiceGetWinnersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WinnerService_GetWinnersClient interface {
	Recv() (*GetWinnersResponse, error)
	grpc.ClientStream
}

type winnerServiceGetWinnersClient struct {
	grpc.ClientStream
}

func (x *winnerServiceGetWinnersClient) Recv() (*GetWinnersResponse, error) {
	m := new(GetWinnersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WinnerServiceServer is the server API for WinnerService service.
type WinnerServiceServer interface {
	GetWinners(*Empty, WinnerService_GetWinnersServer) error
}

// UnimplementedWinnerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWinnerServiceServer struct {
}

func (*UnimplementedWinnerServiceServer) GetWinners(req *Empty, srv WinnerService_GetWinnersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetWinners not implemented")
}

func RegisterWinnerServiceServer(s *grpc.Server, srv WinnerServiceServer) {
	s.RegisterService(&_WinnerService_serviceDesc, srv)
}

func _WinnerService_GetWinners_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WinnerServiceServer).GetWinners(m, &winnerServiceGetWinnersServer{stream})
}

type WinnerService_GetWinnersServer interface {
	Send(*GetWinnersResponse) error
	grpc.ServerStream
}

type winnerServiceGetWinnersServer struct {
	grpc.ServerStream
}

func (x *winnerServiceGetWinnersServer) Send(m *GetWinnersResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _WinnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WinnerService",
	HandlerType: (*WinnerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetWinners",
			Handler:       _WinnerService_GetWinners_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "winner.service.proto",
}
